#**Resolução das questões propostas**

**Discentes responsáveis:** Herick José de Freitas, João Victor Fernandes da Silveira e Lael Gustavo Batista Ribeiro de Lima
\
\
**OBS: Use o comando "CTRL + F9" para executar todas as células de código instantaneamente**

##Definindo o código para resolução com o método da bissecção:

In [ ]:
import sympy as sp

In [ ]:
import pandas as pd

Abaixo se encontra a função criada para iterar o valor da raiz de uma função por meio do *método da bissecção:*

In [ ]:
def bisseccao (a, b, erro, raiz, f):

  # Cria um dataframe que sera mostrado no retorno da funcao
  tabela6 = pd.DataFrame (columns = ['a', 'b', 'Médio (m)', 'f(a)','f(b)', 'f(m)', 'Erro relativo'])

  i = 1

  # Laco de repeticao para calcular as iteracoes
  while(True):
    m =  (a + b) / 2

    # Resolve a equacao para cada extremidade do intervalo e para o ponto medio
    fA = f.subs(x, a)
    fB = f.subs(x, b)
    fm = f.subs(x, m)

    # Adiciona os elementos no dataframe
    tabela6.loc[i] = [a, b, m, fA, fB, fm, abs(f.subs(x, m) - raiz)]

    # Substitui o valor de uma extremidade pelo do ponto medio
    if (fm < raiz):
      b = m
    else:
      a = m

    # Quando o erro for maior, a iteracao final é adicionada no dataframe e o laco para
    if  erro > abs(fm - raiz):
      fA = f.subs(x, a)
      fB = f.subs (x, b)
      fm = f.subs (x, m)
      tabela6.loc[i] = [a, b, m, fA, fB, fm, abs(f.subs(x, m) - raiz)]
      break

    i = i + 1

  return tabela6

##**Questão 1**

**Enunciado:** a velocidade de ascensão de um foguete em voo vertical próximo à superfície terrestre ($v$) pode ser aproximada pela seguinte expressão:
\
$$
v = u \cdot \ln(\frac{M_{0}}{M_{0} - c \cdot t}) + g \cdot t
$$
\
Na qual:
$u$ – velocidade de exaustão relativa ao foguete;
$M_{0}$ – massa do foguete ao ser lançado;
$c$ – taxa de consumo de combustível;
$g$ – Aceleração gravitacional; e
$t$ – tempo (medido a partir do lançamento).
\
\
Considerando $u = 200$ m/s, $M_{0} = 1600$ kg, $g = 9.8$ m/s e $c = 27$ kg/s, determinar o instante em que $v = 100$ m/s. Empregar o método da bissecção para determinar uma raiz aproximada para a equação, com intervalo inicial $[6, 8]$ e tolerância de $0,8\%$. Explicite o erro relativo associado a cada iteração.

In [ ]:
# Definindo os simbolos e as expressões

u, M, c, x, g = sp.symbols("u, M0:1, c, t, g")
vl = u * sp.ln(M / (M - c * x)) + g * x; vl

g*t + u*log(M0/(M0 - c*t))

In [ ]:
# Substituindo os valores especificos das variaveis

v = vl.subs(u, 200).subs(M, 1600).subs(c, 27).subs(g, 9.8); v

9.8*t + 200*log(1600/(1600 - 27*t))

In [ ]:
# Valores iniciais do intervalo: [a, b]
a =  8.0
b =  6.0

# O erro vai ser usado como criterio de parada das iteracoes
erro =  0.08

# Valor ao qual se quer chegar
raiz = 100

In [ ]:
bisseccao(a, b, erro, raiz, v)

,a,b,Médio (m),f(a),f(b),f(m),Erro relativo
1,8.00000,6.000000,7.000000,107.405154410052,80.1500739893761,93.7409912750117,6.25900872498828
2,8.00000,7.000000,7.500000,107.405154410052,93.7409912750117,100.563740639724,0.563740639723662
3,7.50000,7.000000,7.250000,100.563740639724,93.7409912750117,97.1500553630661,2.84994463693387
4,7.50000,7.250000,7.375000,100.563740639724,97.1500553630661,98.8563175711361,1.14368242886388
5,7.50000,7.375000,7.437500,100.563740639724,98.8563175711361,99.7098836479545,0.290116352045516
6,7.50000,7.437500,7.468750,100.563740639724,99.7098836479545,100.136775735593,0.136775735592863
7,7.46875,7.453125,7.453125,100.136775735593,99.9233205952030,99.9233205952030,0.0766794047969768

##**Questão 2**

**Enunciado:** Um cabo telefônico suspenso entre dois postes tem um peso de
quilogramas-força por metro linear. Considerando que a tensão $T$ na
metade do cabo é obtida a partir resolução da seguinte equação:

\
$$
S = \frac{2 \cdot T}{\alpha} \cdot \sinh(\frac{\alpha \cdot L}{2 \cdot T})
$$
\
Na qual: $S$ é o comprimento do cabo e $L$ é a distância entre os postes.

Utilizar o método da bissecção para determinar a tensão $T$ a partir das
seguintes condições: $S = 32$ m, $L = 30$ m, $\alpha = 0.10$ Kgf. Considerar o
intervalo inicial $[2,3]$ e a tolerância superior ou igual a $1\%$.

In [ ]:
#Definindo símbolos e expressões:
x, alpha, L, S = sp.symbols("T, a , L, S")
tensao = (2 * x) / alpha * sp.sinh((alpha * L) / (2 * x)) - S

In [ ]:
# Substituindo os valores especificos das variaveis

ten = tensao.subs(S, 32).subs(L, 30).subs(alpha, 0.10); ten

20.0*T*sinh(1.5/T) - 32

In [ ]:
# Valores iniciais do intervalo: [a, b]
a =  2.0
b =  3.0

# O erro vai ser usado como criterio de parada das iteracoes
erro =  0.01

# Valor ao qual se quer chegar
raiz = 0

In [ ]:
bisseccao(a, b, erro, raiz, ten)

,a,b,Médio (m),f(a),f(b),f(m),Erro relativo
1,2.000000,3.00000,2.500000,0.892669277433200,-0.734281670375157,-0.167320892587931,0.167320892587931
2,2.000000,2.50000,2.250000,0.892669277433200,-0.167320892587931,0.272130745496881,0.272130745496881
3,2.250000,2.50000,2.375000,0.272130745496881,-0.167320892587931,0.0346184300727614,0.0346184300727614
4,2.375000,2.50000,2.437500,0.0346184300727614,-0.167320892587931,-0.0703308093591879,0.0703308093591879
5,2.375000,2.43750,2.406250,0.0346184300727614,-0.0703308093591879,-0.0189045571438342,0.0189045571438342
6,2.390625,2.40625,2.390625,0.00758776265276140,-0.0189045571438342,0.00758776265276140,0.00758776265276140

##**Questão 6**

**Enunciado:** em engenharia ambiental, a equação abaixo pode ser usada para calcular o nível de oxigênio em um rio, após a chegada de uma descarga de esgoto.
\
\
$$
C = 10 - 15(e^{-0.1x} - e^{-0.5x})
$$
\
\
Em que $x$ é a distância rio abaixo.
\
Determine em que ponto, após a descarga de esgoto, o nível de oxigênio terá caído para $4$. Calcule com erro menor que $1\%$.

In [ ]:
# Definindo os simbolos e as expressões
x = sp.symbols("x")

In [ ]:
# Substituindo os valores especificos das variaveis
taxa = 10 - 15 * (sp.exp(-0.1*x) - sp.exp(-0.5*x)); taxa

10 + 15*exp(-0.5*x) - 15*exp(-0.1*x)

In [ ]:
# Valores iniciais do intervalo: [a, b]
a =  9.0
b =  8.0

# O erro vai ser usado como criterio de parada das iteracoes
erro =  0.04

# Valor ao qual se quer chegar
raiz = 4

In [ ]:
# Chama e calcula a funcao
bisseccao(a, b, erro, raiz, taxa)

,a,b,Médio (m),f(a),f(b),f(m),Erro relativo
1,9.000,8.00,8.500,4.06809005196465,3.53480012157269,3.80273952940409,0.197260470595911
2,9.000,8.50,8.750,4.06809005196465,3.80273952940409,3.93589183845888,0.0641081615411156
3,8.875,8.75,8.875,4.00212683133337,3.93589183845888,4.00212683133337,0.00212683133337332